on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
jobs:
  discussion_created:
    runs-on: ubuntu-latest
    if: github.event.discussion && !github.event.comment
    steps:
      - run: |
          curl -X POST -d '{ "text": "dummy", "discussion_title": ${{ toJSON(github.event.discussion.title) }}, "discussion_body": ${{ toJSON(github.event.discussion.body) }}, "discussion_url": ${{ toJSON(github.event.discussion.html_url) }}, "discussion_category": ${{ toJSON(github.event.discussion.category.name) }}, "posted_user": ${{ toJSON(github.event.discussion.user) }} }' ${{ secrets.SLACK_WEBHOOK_URL }}
  discussion_commented:
    runs-on: ubuntu-latest
    if: github.event.discussion && github.event.comment
    steps:
      - run: |
          curl -X POST -d '{ "text": "dummy", "comment_title": ${{ toJSON(github.event.comment.title) }}, "comment_body": ${{ toJSON(github.event.comment.body) }}, "comment_url": ${{ toJSON(github.event.comment.html_url) }}, "comment_category": ${{ toJSON(github.event.comment.category.name) }}, "posted_user": ${{ toJSON(github.event.comment.user) }} }' ${{ secrets.SLACK_WEBHOOK_URL }}
