on:
  discussion:
    types: [created]
  discussion_comment:
    types: [created]
jobs:
  discussion_created:
    runs-on: ubuntu-latest
    if: github.event.discussion && !github.event.comment
    steps:
      - run: |
          curl -X POST -d '{ "text": "dummy: ${{ github.event.discussion.title }}, ${{ github.event.discussion.body }}, ${{ github.event.discussion.html_url }}, ${{ github.event.discussion.category.name }}, ${{ github.event.discussion.user }}" }' ${{ secrets.SLACK_WEBHOOK_URL }}
  discussion_commented:
    runs-on: ubuntu-latest
    if: github.event.discussion && github.event.comment
    steps:
      - run: |
          curl -X POST -d '{ "text": "dummy: ${{ github.event.comment.title }}, ${{ github.event.comment.body }}, ${{ github.event.comment.html_url }}, ${{ github.event.comment.category.name }}, ${{ github.event.comment.user }}" }' ${{ secrets.SLACK_WEBHOOK_URL }}
